"""add open source model

Revision ID: 26c45bbd8116
Revises: df2ad0af02cf
Create Date: 2026-07-05 18:30:57.995689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c45bbd8116'
down_revision = 'df2ad0af02cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_source_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('developer_lab', sa.String(length=200), nullable=False),
    sa.Column('license', sa.String(length=100), nullable=False),
    sa.Column('param_count_billions', sa.Integer(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('open_source_models')
    # ### end Alembic commands ###
