"""add source_note and estimate flags

Revision ID: a7726e2719bc
Revises: fa7e9addd46e
Create Date: 2026-07-06 17:00:16.227220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7726e2719bc'
down_revision = 'fa7e9addd46e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_source_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_note', sa.Text(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('price_is_estimate', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('power_is_estimate', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('power_is_estimate')
        batch_op.drop_column('price_is_estimate')
        batch_op.drop_column('source_note')

    with op.batch_alter_table('open_source_models', schema=None) as batch_op:
        batch_op.drop_column('source_note')

    # ### end Alembic commands ###
