"""add about_developer and best_for to open source model

Revision ID: bf2037ef71b3
Revises: a7726e2719bc
Create Date: 2026-07-07 20:44:23.210571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2037ef71b3'
down_revision = 'a7726e2719bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_source_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_developer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('best_for', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('open_source_models', schema=None) as batch_op:
        batch_op.drop_column('best_for')
        batch_op.drop_column('about_developer')

    # ### end Alembic commands ###
