"""add quote request model

Revision ID: fa7e9addd46e
Revises: 26c45bbd8116
Create Date: 2026-07-05 20:03:54.182099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7e9addd46e'
down_revision = '26c45bbd8116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_contact', sa.String(length=200), nullable=False),
    sa.Column('build_description', sa.Text(), nullable=False),
    sa.Column('total_price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_requests')
    # ### end Alembic commands ###
